### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nikumar1013** [kushSharma924/meal-planner-app#3]
Before creating your pull request for week one could you please update the README with instructions on how to run your code locally so that I'll be able to do so on my end?

Here's an example template you can use: https://github.com/othneildrew/Best-README-Template/blob/master/README.md

README files are written in a markup language called markdown that formats text when rendered. When you visit the link if could click "preview" it will show you the formatted appearance and if you click "code" you will see the raw markdown. Feel free to copy the raw markdown code and edit in VSCode however you see fit. Then you'll commit and push the changes as you would for any other file change. VSCode will also show you the preview side-by-side as you edit.

Have fun!

**Comment by kushSharma924** [comment]
Sure, will do that on Saturday!

**Comment by kushSharma924** [comment]
I have updated the readme using the template!

**Comment by kushSharma924** [comment]
I have updated the README using the template!
