### ISSUE TITLE
Additional UI Changes to Consider

### ISSUE THREAD

**Issue by nikumar1013** [kushSharma924/meal-planner-app#6]
Have some additional UI improvements for you to consider adding. 

The spacing between each question and the corresponding dropdown seems to be a little too much now. I think it will look a lot cleaner if we reduce that spacing a bit. On the flip side, let's maybe increase the spacing above the "Generate Recipes" button.

I also think the "Enter Keywords to Describe Your Meal" text should be reduced in size for a cleaner look. I think the text box as a whole can actually be reduced so that when the user types the text is equivalent in side to the fixed on screen questions.

Lastly, as you can see in the screenshot, at the top of the screen in my tabs this is still called "React App" and the little icon (called a favicon) is still the React logo. Let's definitely update that (should be an easy change).

As always, let me know if you have any questions!

<img width="1325" alt="image" src="https://github.com/kushSharma924/meal-planner-app/assets/31876604/264513fd-30e6-466d-aba7-dd5a63d444e1">

**Comment by kushSharma924** [comment]
I have updated the UI with those changes. Here is what it looks like now:
![Screenshot 2024-02-18 at 6 04 44 AM](https://github.com/kushSharma924/meal-planner-app/assets/106769448/d836330e-6589-414a-bb62-a4eeace1bde4)
